# Generated by Django 3.0.3 on 2021-01-20 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20210120_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job_requrement',
            new_name='job_requirement',
        ),
    ]
