# Generated by Django 2.2.13 on 2021-01-23 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20210120_2243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': '职位信息', 'verbose_name_plural': '职位信息'},
        ),
    ]
